-- Create chatbot_settings table
CREATE TABLE IF NOT EXISTS chatbot_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  is_enabled BOOLEAN DEFAULT true,
  position VARCHAR(20) DEFAULT 'bottom-right',
  theme_color VARCHAR(7) DEFAULT '#16a34a',
  welcome_message TEXT,
  quick_replies JSONB,
  ai_enabled BOOLEAN DEFAULT true,
  gemini_api_key TEXT,
  ai_model VARCHAR(100) DEFAULT 'gemini-2.0-flash-lite',
  max_tokens INTEGER DEFAULT 500,
  daily_ai_limit INTEGER DEFAULT 1500,
  keyword_match_priority INTEGER DEFAULT 70,
  data_query_priority INTEGER DEFAULT 20,
  ai_query_priority INTEGER DEFAULT 10,
  faqs JSONB,
  company_name VARCHAR(100) DEFAULT '달래마켓',
  company_phone VARCHAR(20) DEFAULT '010-2688-1388',
  business_hours VARCHAR(100) DEFAULT '평일 09:00 - 18:00',
  offline_message TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
